## This pair of functions will compute the inversion of a matrix, and at the same time cache it inversed value.
## This is useful if the inversion of the same matrix is required later.

## This funtion will create a special type of matrix object which can also stored its inversed value
makeCacheMatrix <- function(x = matrix()) {
        inversed_matrix <- NULL
        set <- function(y) {
        x <<- y
        inversed_matrix <<- NULL
        }
        get <- function() x
        setCache <- function(inverse) inversed_matrix <<- inverse
        getCache <- function() inversed_matrix
        list(set = set, get = get, setCache = setCache, getCache = getCache)
}

## This function will inverse the matrix, and cache the inversed value.
## If the invesed value of the matrix is already pre-computed, it will skip the inverstion and just return the catched value.
## The input matrix for this function has to be generated by the makeCacheMatrix function above.
cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
        inversed_matrix <- x$getCache()
        if(!is.null(inversed_matrix)) {
                        message("getting cached data")
                        return(inversed_matrix)
        }
        matrix <- x$get()
        inversed_matrix <- solve(matrix, ...)
        x$setCache(inversed_matrix)
        inversed_matrix
}
